services:
  app:
    build: .
    container_name: sexgram-backend
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    env_file: .env
    depends_on:
      - postgres
      - redis
      - qdrant
    command: ["sh", "-c", "chmod +x dev.sh && ./dev.sh"]
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    env_file: .env
    volumes:
      - ./container_data/qdrant:/qdrant/storage
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    volumes:
      - ./container_data/postgres:/var/lib/postgresql
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - ./container_data/redis:/data

volumes:
  postgres_data:
  redis_data:
